import { ReactNode } from "react";
import Image from "next/image";
import Logo from "../public/logo.png";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";

const inter = Inter({ subsets: ["latin"] });

interface LayoutProps {
  children: ReactNode;
}

export const metadata: Metadata = {
  title: "POC Nextjs Blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps) {
  const header = (
    <div className="header">
      <div className="header__wrapper">
        <Image
          src={Logo}
          width={40}
          height={40}
          quality={100}
          placeholder="blur"
          className="header__logo"
          alt="logo"
        />
        <h1 className="header__title">POC Nextjs Blog</h1>
      </div>
    </div>
  );
  const footer = <footer></footer>;

  return (
    <html lang="en">
      <body className={inter.className}>
        {header}
        {children}
        {footer}
      </body>
    </html>
  );
}
